### ISSUE TITLE
Image processing with `loading="lazy"` attribute in template

### ISSUE THREAD

**Issue by RickStanley** [sarioglu/parcel-plugin-ejs-template#3]
Hi, I've noticed when I use an image tag inside a template, with `loading="lazy"`, parcel doesn't process the image.

I expected:
```html
<img loading="lazy" src="img/image.png">
```
to be processed by parcel, becoming something like:
```html
<img loading="lazy" src="/image.HASH.png">
```
but I get  `<img loading="lazy" src="undefined">` .

Without `loading="lazy"` attribute, it works just fine.

devDependencies:

    "parcel-bundler": "^1.12.4",
    "parcel-plugin-ejs-template": "^0.1.2",

Thanks for the plugin :)

**Comment by sarioglu** [comment]
Hi @RickStanley,
I'm afraid I couldn't reproduce the issue. I don't see any difference between using  with or without `loading="lazy"`. Since it is just another html attribute, I cannot think of any reason to cause that.
