### ISSUE TITLE
When using the plugin, should the entryfile be the EJS file?

### ISSUE THREAD

**Issue by csanaot** [sarioglu/parcel-plugin-ejs-template#4]
I'm a little new to parcel and I'm trying to figure out how to use the plugin to package the files in the view folder. Is there a tutorial or docs I can refer?
Btw,Thanks for the plugin

**Comment by sarioglu** [comment]
Hi @csanaot ,
This plugin lets parcel to build `.ejs` files. For the basic case, you can add `build: parcel build index.ejs` into the scripts of your `package.json` and run `npm run build`.

You can refer to https://parceljs.org/getting_started.html for a step-by-step guide to use parcel bundler.
